services:
  app:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: resume-screener
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/resumes:/app/resumes
      - ./data:/app/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: resume_screener_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
